"use client";

import { useEffect, useRef, useState } from "react";
import type { FormEvent } from "react";

type Message = { from: "bot" | "user"; text: string };
const welcome: Message = { from: "bot", text: "Hi, I’m Node—your crypto field guide. Ask me about networks, wallets, security, DeFi, or how to research a claim." };
const suggestions = [["Compare BTC and ETH", "How are Bitcoin and Ethereum different?"], ["Wallet safety", "How do I keep a crypto wallet safe?"], ["DeFi risks", "What are the main risks of DeFi?"], ["Spot a scam", "How can I spot a crypto scam?"]] as const;

function answerQuestion(question: string) {
  const q = question.toLowerCase().replace(/[’']/g, "'");
  if (/^(hi|hello|hey|good morning|good afternoon)\b/.test(q)) return "Hello! I can help you understand crypto concepts and research risks in plain language. What are you exploring?";
  if (/thank|helpful|got it/.test(q)) return "You’re welcome. Keep verifying important details with primary sources—and feel free to ask a follow-up.";
  if (/bitcoin|btc/.test(q) && /ethereum|eth/.test(q)) return "Bitcoin is primarily designed as scarce, censorship-resistant monetary settlement. Ethereum is a programmable platform for smart contracts and applications. Bitcoin favors a narrower base layer; Ethereum accepts more complexity for composable applications. Compare their consensus, issuance, fees, custody, and the job you expect each network to perform.";
  if (/bitcoin|\bbtc\b/.test(q)) return "Bitcoin is a decentralized monetary and settlement network with a maximum supply of 21 million BTC. Proof of work helps secure its history. Strengths include predictable issuance and censorship-resistant settlement; tradeoffs include limited base-layer throughput, energy use, volatility, and self-custody responsibility.";
  if (/ethereum|\beth\b|gas fee|evm/.test(q)) return "Ethereum is a proof-of-stake network for programmable smart contracts. ETH pays transaction fees, called gas, and helps secure the network through staking. Its composability supports many applications, but contract bugs, approvals, bridges, and layer-two assumptions add risk.";
  if (/solana|\bsol\b/.test(q)) return "Solana is a proof-of-stake network optimized for fast, low-cost interaction. Its parallel runtime supports trading, payments, and consumer applications. Research validator requirements, client diversity, reliability, application permissions, token economics, and whether usage remains durable when incentives change.";
  if (/seed phrase|recovery phrase|private key/.test(q)) return "A seed or recovery phrase can recreate control of a wallet. Never share it or type it into a message, form, or website after setup. Store it offline in a secure, durable place. Anyone who obtains it can usually move the assets without reversal.";
  if (/wallet|custody|hardware wallet/.test(q)) return "A wallet manages the keys used to authorize transactions; it does not literally hold coins. Use reputable software, protect the recovery phrase offline, secure the device, verify addresses, and send a small test first. A hardware wallet reduces online key exposure but cannot protect you from approving a malicious transaction.";
  if (/scam|phish|fraud|rug|guaranteed return/.test(q)) return "Warning signs include urgency, guaranteed returns, impersonated support, seed-phrase requests, unexpected approvals, and look-alike domains. Pause, navigate to the official site independently, verify claims through multiple sources, and never send funds to unlock or recover other funds.";
  if (/defi|lending|liquidity pool|yield farm/.test(q)) return "DeFi uses smart contracts for trading, lending, and borrowing. Key risks include exploits, oracle failures, unstable collateral, liquidation, thin liquidity, administrator control, and yields funded by temporary token incentives. Identify where the yield comes from and what can cause loss.";
  if (/bridge|bridging|wrapped token/.test(q)) return "A bridge moves value or messages between networks, often by locking an asset on one chain and issuing a representation elsewhere. That adds contract, validator, custody, and liquidity assumptions. Verify the official bridge, destination asset, withdrawal path, and upgrade controls.";
  if (/staking|validator|proof of stake/.test(q)) return "Staking commits assets to help secure a proof-of-stake network in exchange for protocol rewards. Risks can include volatility, lockups, slashing, validator failure, contract exposure, and liquid-staking token depegs. Rewards are not risk-free interest.";
  if (/proof of work|mining|miner/.test(q)) return "Proof of work uses computational competition to order transactions and make history costly to rewrite. Miners propose blocks while nodes verify the rules. Its security model is established, but it requires energy, specialized equipment, and a healthy mining and fee economy.";
  if (/stablecoin|usdc|usdt|dai/.test(q)) return "A stablecoin aims to track another asset, usually a currency. Stability depends on reserves, collateral, redemption, governance, banking access, and smart contracts. 'Stable' describes the target—not a guarantee—so investigate the issuer and redemption process.";
  if (/nft|collectible/.test(q)) return "An NFT is a unique token record that can represent ownership or access. The token, media, copyright, and community benefits are separate. Check metadata storage, granted rights, contract permissions, marketplace liquidity, and creator authenticity.";
  if (/fee|transaction cost|why.*expensive/.test(q)) return "Network fees pay for scarce block space and deter spam. They can rise when demand exceeds capacity. Check the network, fee estimate, application fees, bridge costs, and whether a lower-cost layer introduces additional assumptions.";
  if (/buy|sell|invest|price|worth it|good investment|which coin/.test(q)) return "I can’t predict prices or tell you what to buy. Define the asset’s purpose, evidence of demand, supply and incentives, custody plan, downside scenarios, time horizon, and the amount you can afford to lose. Verify current market data independently.";
  if (/risk|safe|danger/.test(q)) return "Crypto risk is layered: volatility, custody mistakes, malicious approvals, contract bugs, liquidity, leverage, governance, and regulation can all matter. Name each dependency, test with a small amount, avoid urgency, and decide what evidence would make you stop.";
  if (/research|verify|source|due diligence|evaluate/.test(q)) return "Start with the problem being solved, then trace who controls upgrades, custody, issuance, incentives, and critical data. Prefer primary documentation and transparent data. Compare independent sources, list unresolved assumptions, and write down what would change your mind.";
  return "I’m not fully sure what part you want unpacked. Try naming the network, product, or risk—for example: ‘How do wallet approvals work?’, ‘Compare Bitcoin and Ethereum,’ or ‘What should I verify before using DeFi?’";
}

export default function CryptoGuide() {
  const [open, setOpen] = useState(false);
  const [messages, setMessages] = useState<Message[]>([welcome]);
  const [input, setInput] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);
  const messageRef = useRef<HTMLDivElement>(null);
  useEffect(() => { const show = () => setOpen(true); window.addEventListener("open-crypto-guide", show); return () => window.removeEventListener("open-crypto-guide", show); }, []);
  useEffect(() => { if (open) setTimeout(() => inputRef.current?.focus(), 50); }, [open]);
  useEffect(() => { messageRef.current?.scrollTo({ top: messageRef.current.scrollHeight, behavior: "smooth" }); }, [messages]);
  function ask(question: string) { setMessages((current) => [...current, { from: "user", text: question }, { from: "bot", text: answerQuestion(question) }]); }
  function send(event: FormEvent) { event.preventDefault(); const question = input.trim(); if (!question) return; ask(question); setInput(""); }
  return <><button type="button" className="chat-launch" onClick={() => setOpen(!open)} aria-label={open ? "Close AI crypto guide" : "Open AI crypto guide"} aria-expanded={open} aria-controls="crypto-guide">{open ? "×" : "✦"}</button>{open && <aside className="chat" id="crypto-guide" aria-labelledby="guide-title"><header><div><span aria-hidden="true">✦</span><p><b id="guide-title">Node</b><small><i aria-hidden="true"/> AI crypto guide</small></p></div><div className="chat-header-actions"><button type="button" onClick={() => setMessages([welcome])} aria-label="Clear conversation">↺</button><button type="button" onClick={() => setOpen(false)} aria-label="Close chat">×</button></div></header><div className="messages" ref={messageRef} aria-live="polite" aria-relevant="additions">{messages.map((message, index) => <div className={`message ${message.from}`} key={`${index}-${message.text.slice(0, 12)}`}>{message.text}</div>)}</div>{messages.length === 1 && <div className="chips" aria-label="Suggested questions">{suggestions.map(([label, question]) => <button type="button" key={label} onClick={() => ask(question)}>{label}</button>)}</div>}<form onSubmit={send}><label className="sr-only" htmlFor="crypto-question">Ask Node a crypto question</label><input ref={inputRef} id="crypto-question" value={input} onChange={(event) => setInput(event.target.value)} placeholder="Ask a crypto question…" autoComplete="off"/><button type="submit" aria-label="Send question">↑</button></form><small className="disclaimer">Educational guidance only · Verify current details before acting.</small></aside>}</>;
}
